name: Makefile CI

on:
  push:
    branches: [ "winrt" ]
  pull_request:
    branches: [ "winrt" ]

jobs: 
  build:

    runs-on: ubuntu-20.04

    steps:
    - name: Install gcc
      run: sudo apt-get install gcc-arm-linux-gnueabihf 
      
    - uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4.6.1
      with:
         python-version: 2.7
    - name: step1
      run: make -C BaseTools
    - name: step2
      run: source edksetup.sh

    - name: step3
      run: export GCC49_ARM_PREFIX=arm-linux-gnueabihf-

    - name: step4
      run:  export GCC49_ARM_PREFIX=arm-linux-gnueabihf-&& export SOURCE_DEBUG_ENABLE=TRUE && export DEBUG_ON_SERIAL_PORT && export WORKSPACE=/home/runner/work/edk2-winrt/edk2-winrt && export EDK_TOOLS_PATH=/home/runner/work/edk2-winrt/edk2-winrt/BaseTools && export CONF_PATH=/home/runner/work/edk2-winrt/edk2-winrt/Conf && cd ./BaseTools/BinWrappers/PosixLike && export PATH=$PATH:/home/runner/work/edk2-winrt/edk2-winrt/BaseTools/BinWrappers/PosixLike && ./build -a ARM -t GCC49 -b RELEASE -p ArmVirtPkg/ArmVirtQemuWinRt.dsc && cd ../../../
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.2
      with:
        name: QEMU_EFI.fd
        path: ./Build/ArmVirtQemuWinRt-ARM/RELEASE_GCC49/FV/QEMU_EFI.fd
